services:
  - type: web
    name: shree-parth-academy
    runtime: image
    plan: free
    region: frankfurt
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
